[package]
name = "actix_chat_web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
serde= "1"
actix-files = "0.5.0"
actix-web-actors = "3.0.0"
actix = "0.10.0"